import artifactJson from '@/lib/electionAggregates/bahia-second-round-2026.json'
import type { SecondRoundRole } from '@/lib/secondRoundRole'
import { computeSectionPotential, type SectionPotential } from '@/lib/sectionPotential'

/**
 * Committed Bahia 2º-turno baseline (Lula × Flávio): official TSE 2026 president
 * T1 per section (aggregated to the campaign's municipality geography — Salvador
 * split by ZE), joined with the 2022 presidential slice and Solla's 2026 federal
 * result. Generated by `pnpm build:second-round` from
 * `public/dados/potencial-secao-2026/BA.json` + the internal 2º-turno analysis,
 * validated against `bahia-federal-baseline.json` and the audited BA totals —
 * never computed at build/request time.
 *
 * Read-only and pure: the loader only projects the artifact and runs the SAME
 * `computeSectionPotential` the public `/potencial` page uses, so the report's
 * X₁/X₂ can never drift from the site's scenario.
 */

export type BahiaSecondRoundUnit = {
  /** Display name ("Jaguaquara" / "Salvador — ZE 19"). */
  name: string
  kind: 'municipio' | 'zona'
  tseCityCode: string
  ibgeCode: string
  /** Zone number for Salvador ZE units; null for whole municipalities. */
  zone: number | null
  /** Deterministic campaign role (`secondRoundRole.ts`). */
  role: SecondRoundRole
  /** Lula's votes in the 2022 presidential race. */
  lula22: number
  /** Lula's votes in the 1º turno 2026. */
  lula26: number
  /** `lula26 − lula22` (negative = lost votes). */
  dLula: number
  /** Bolsonaro 2022 / Flávio 2026 (the same adversary seat across cycles). */
  adversary22: number
  adversary26: number
  dAdversary: number
  /** Solla (federal deputy 1313): 2022 and 2026 nominal votes. */
  solla22: number
  solla26: number
  dSolla: number
  aptos22: number
  aptos26: number
  comparecimento22: number
  comparecimento26: number
  abstencao22: number
  abstencao26: number
  /** Blank + null votes (comparecimento − válidos). */
  brancosNulos22: number
  brancosNulos26: number
  validos22: number
  validos26: number
}

type BahiaSecondRoundArtifact = {
  version: number
  generatedAt: string
  scope: string
  provenance: string
  sources: Record<string, string>
  pins: Record<string, number>
  totals: Record<string, number>
  units: Record<string, BahiaSecondRoundUnit>
}

const artifact = artifactJson as BahiaSecondRoundArtifact

export const BAHIA_SECOND_ROUND_GENERATED_AT = artifact.generatedAt

/** One catalog unit (slug from `municipalityCatalog`) or `null` when unknown. */
export const getBahiaSecondRoundUnit = (slug: string): BahiaSecondRoundUnit | null =>
  artifact.units[slug] ?? null

export const bahiaSecondRoundTotals = artifact.totals

/**
 * The 2º-turno scenario for one unit — X₁ (votes already available inside the
 * 1º-turno comparecimento: nulls + blanks + all third-party votes) and X₂
 * (X₁ + absentees), with the hypothetical 2nd-round shares. Reuses the public
 * `/potencial` formula; `null` when the raw counts are inconsistent.
 */
export const secondRoundPotentialOf = (unit: BahiaSecondRoundUnit): SectionPotential | null => {
  const result = computeSectionPotential({
    aptos: unit.aptos26,
    comparecimento: unit.comparecimento26,
    lula: unit.lula26,
    flavio: unit.adversary26,
    validos: unit.validos26,
  })
  return result.available ? result.potential : null
}

/** Lula's share of the 1º-turno valid votes (2022 / 2026), in percent. */
export const secondRoundLulaShares = (
  unit: BahiaSecondRoundUnit,
): { share22: number; share26: number; deltaPp: number } => {
  const share22 = unit.validos22 > 0 ? (unit.lula22 / unit.validos22) * 100 : 0
  const share26 = unit.validos26 > 0 ? (unit.lula26 / unit.validos26) * 100 : 0
  return { share22, share26, deltaPp: share26 - share22 }
}

/** Solla's 2026 votes as a share of Lula's 2026 votes (the local brand ratio). */
export const secondRoundSollaShareOfLula = (unit: BahiaSecondRoundUnit): number | null =>
  unit.lula26 > 0 ? (unit.solla26 / unit.lula26) * 100 : null

/** Δ adversary ÷ |Δ Lula| — how much of Lula's loss the adversary captured. */
export const secondRoundAdversaryCapturePct = (unit: BahiaSecondRoundUnit): number | null => {
  if (unit.dLula >= 0) return null
  return (unit.dAdversary / Math.abs(unit.dLula)) * 100
}
