import { z } from 'zod'

import { CONTENT_EVENT_TYPES } from '@/lib/contentEvents'

/**
 * C213 — the wire contract of the public `POST /api/content-events`: the event
 * type from the shared vocabulary and the PUBLIC slug of a published piece.
 * The client never names the internal subject id — the route resolves the slug
 * against the published read, so an unpublished or unknown piece writes
 * nothing. A malformed body is refused before any query (and the beacon ignores
 * every response anyway).
 */

/** Slugs are generated by `contentPieceSlugBase` (lowercase groups + hyphens). */
const CONTENT_PIECE_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/
const CONTENT_PIECE_SLUG_MAX_LENGTH = 120

export const contentEventRequestSchema = z.object({
  type: z.enum(CONTENT_EVENT_TYPES),
  pieceSlug: z
    .string()
    .trim()
    .min(1)
    .max(CONTENT_PIECE_SLUG_MAX_LENGTH)
    .regex(CONTENT_PIECE_SLUG_PATTERN),
})
