import { MigrateDownArgs, MigrateUpArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db }: MigrateUpArgs): Promise<void> {
  // Destructive remodel: Praça → Município (product decision 2026-07-23).
  await db.execute(sql`
    DELETE FROM "campaign_invite";
    DELETE FROM "supporter";
    DELETE FROM "supporter_import_batch";
    DELETE FROM "action_plan";
    DELETE FROM "vote_pledge";
    DELETE FROM "campaign_demand";
    DELETE FROM "plaza_update";
    DELETE FROM "leadership";
    DELETE FROM "organization";
  `)

  await db.execute(sql`
    DROP TABLE IF EXISTS "plaza_update" CASCADE;
    DROP TABLE IF EXISTS "plaza_rels" CASCADE;
    DROP TABLE IF EXISTS "plaza_strengths" CASCADE;
    DROP TABLE IF EXISTS "plaza_risks" CASCADE;
    DROP TABLE IF EXISTS "plaza" CASCADE;
    DROP TYPE IF EXISTS "public"."enum_plaza_kind";
    DROP TYPE IF EXISTS "public"."enum_plaza_priority";
    DROP TYPE IF EXISTS "public"."enum_plaza_political_trend_status";
    DROP TYPE IF EXISTS "public"."enum_plaza_update_kind";
  `)

  await db.execute(sql`
    CREATE TYPE "public"."enum_municipality_kind" AS ENUM('municipio', 'zona');
    CREATE TYPE "public"."enum_municipality_priority" AS ENUM('alta', 'normal');
    CREATE TYPE "public"."enum_municipality_political_trend_status" AS ENUM('favoravel', 'neutra', 'desfavoravel');
    CREATE TYPE "public"."enum_municipality_update_kind" AS ENUM('semanal', 'urgente', 'nota');

    CREATE TABLE "municipality_strengths" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "text" varchar NOT NULL
    );

    CREATE TABLE "municipality_risks" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "text" varchar NOT NULL
    );

    CREATE TABLE "municipality" (
      "id" serial PRIMARY KEY NOT NULL,
      "name" varchar NOT NULL,
      "slug" varchar NOT NULL,
      "kind" "enum_municipality_kind" NOT NULL,
      "city" varchar NOT NULL,
      "region" varchar NOT NULL,
      "ibge_code" varchar NOT NULL,
      "tse_city_code" varchar NOT NULL,
      "zone_number" numeric,
      "priority" "enum_municipality_priority" DEFAULT 'normal',
      "vote_goals_good" numeric,
      "vote_goals_regular" numeric,
      "vote_goals_minimum" numeric,
      "expected_votes_pessimistic" numeric,
      "expected_votes_central" numeric,
      "expected_votes_optimistic" numeric,
      "political_trend_status" "enum_municipality_political_trend_status",
      "political_trend_note" varchar,
      "political_trend_recorded_by_id" integer,
      "political_trend_recorded_at" timestamp(3) with time zone,
      "dobradinha_notes" varchar,
      "next_steps" varchar,
      "last_update_at" timestamp(3) with time zone,
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE TABLE "municipality_rels" (
      "id" serial PRIMARY KEY NOT NULL,
      "order" integer,
      "parent_id" integer NOT NULL,
      "path" varchar NOT NULL,
      "campaign_user_id" integer
    );

    CREATE TABLE "municipality_update" (
      "id" serial PRIMARY KEY NOT NULL,
      "municipality_id" integer NOT NULL,
      "author_id" integer NOT NULL,
      "kind" "enum_municipality_update_kind" DEFAULT 'semanal' NOT NULL,
      "worked" varchar,
      "failed" varchar,
      "needs" varchar,
      "active_volunteers" numeric,
      "new_supports" numeric,
      "body" varchar,
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE UNIQUE INDEX "municipality_slug_idx" ON "municipality" USING btree ("slug");
    CREATE UNIQUE INDEX "municipality_name_idx" ON "municipality" USING btree ("name");
  `)

  await db.execute(
    sql`ALTER TYPE "public"."enum_campaign_user_role" ADD VALUE IF NOT EXISTS 'candidate'`,
  )
  await db.execute(
    sql`ALTER TYPE "public"."enum_supporter_source" ADD VALUE IF NOT EXISTS 'lideranca'`,
  )

  await db.execute(sql`
    ALTER TABLE "supporter" RENAME COLUMN "plaza_id" TO "municipality_id";
    ALTER TABLE "vote_pledge" RENAME COLUMN "plaza_id" TO "municipality_id";
    ALTER TABLE "action_plan" RENAME COLUMN "plaza_id" TO "municipality_id";
    ALTER TABLE "campaign_demand" RENAME COLUMN "plaza_id" TO "municipality_id";
    ALTER TABLE "leadership_rels" RENAME COLUMN "plaza_id" TO "municipality_id";
    ALTER TABLE "organization_rels" RENAME COLUMN "plaza_id" TO "municipality_id";
  `)

  await db.execute(sql`
    INSERT INTO "municipality" ("name", "slug", "kind", "city", "region", "ibge_code", "tse_city_code", "zone_number")
    VALUES
    ('Abaíra', 'abaira', 'municipio'::"public"."enum_municipality_kind", 'Abaíra', 'Chapada Diamantina', '2900108', '33014', NULL),
  ('Abaré', 'abare', 'municipio'::"public"."enum_municipality_kind", 'Abaré', 'Itaparica', '2900207', '33030', NULL),
  ('Acajutiba', 'acajutiba', 'municipio'::"public"."enum_municipality_kind", 'Acajutiba', 'Litoral Norte e Agreste Baiano', '2900306', '33057', NULL),
  ('Adustina', 'adustina', 'municipio'::"public"."enum_municipality_kind", 'Adustina', 'Semiárido Nordeste II', '2900355', '33065', NULL),
  ('Água Fria', 'agua-fria', 'municipio'::"public"."enum_municipality_kind", 'Água Fria', 'Portal do Sertão', '2900405', '33073', NULL),
  ('Aiquara', 'aiquara', 'municipio'::"public"."enum_municipality_kind", 'Aiquara', 'Médio Rio de Contas', '2900603', '33111', NULL),
  ('Alagoinhas', 'alagoinhas', 'municipio'::"public"."enum_municipality_kind", 'Alagoinhas', 'Litoral Norte e Agreste Baiano', '2900702', '33138', NULL),
  ('Alcobaça', 'alcobaca', 'municipio'::"public"."enum_municipality_kind", 'Alcobaça', 'Extremo Sul', '2900801', '33154', NULL),
  ('Almadina', 'almadina', 'municipio'::"public"."enum_municipality_kind", 'Almadina', 'Litoral Sul', '2900900', '33170', NULL),
  ('Amargosa', 'amargosa', 'municipio'::"public"."enum_municipality_kind", 'Amargosa', 'Vale do Jiquiriçá', '2901007', '33197', NULL),
  ('Amélia Rodrigues', 'amelia-rodrigues', 'municipio'::"public"."enum_municipality_kind", 'Amélia Rodrigues', 'Portal do Sertão', '2901106', '33219', NULL),
  ('América Dourada', 'america-dourada', 'municipio'::"public"."enum_municipality_kind", 'América Dourada', 'Irecê', '2901155', '30716', NULL),
  ('Anagé', 'anage', 'municipio'::"public"."enum_municipality_kind", 'Anagé', 'Sudoeste Baiano', '2901205', '33235', NULL),
  ('Andaraí', 'andarai', 'municipio'::"public"."enum_municipality_kind", 'Andaraí', 'Chapada Diamantina', '2901304', '33251', NULL),
  ('Andorinha', 'andorinha', 'municipio'::"public"."enum_municipality_kind", 'Andorinha', 'Piemonte Norte do Itapicuru', '2901353', '33260', NULL),
  ('Angical', 'angical', 'municipio'::"public"."enum_municipality_kind", 'Angical', 'Bacia do Rio Grande', '2901403', '33278', NULL),
  ('Anguera', 'anguera', 'municipio'::"public"."enum_municipality_kind", 'Anguera', 'Portal do Sertão', '2901502', '33294', NULL),
  ('Antas', 'antas', 'municipio'::"public"."enum_municipality_kind", 'Antas', 'Semiárido Nordeste II', '2901601', '33316', NULL),
  ('Antônio Cardoso', 'antonio-cardoso', 'municipio'::"public"."enum_municipality_kind", 'Antônio Cardoso', 'Portal do Sertão', '2901700', '33332', NULL),
  ('Antônio Gonçalves', 'antonio-goncalves', 'municipio'::"public"."enum_municipality_kind", 'Antônio Gonçalves', 'Piemonte Norte do Itapicuru', '2901809', '33359', NULL),
  ('Aporá', 'apora', 'municipio'::"public"."enum_municipality_kind", 'Aporá', 'Litoral Norte e Agreste Baiano', '2901908', '33375', NULL),
  ('Apuarema', 'apuarema', 'municipio'::"public"."enum_municipality_kind", 'Apuarema', 'Médio Rio de Contas', '2901957', '33405', NULL),
  ('Araças', 'aracas', 'municipio'::"public"."enum_municipality_kind", 'Araças', 'Litoral Norte e Agreste Baiano', '2902054', '33383', NULL),
  ('Aracatu', 'aracatu', 'municipio'::"public"."enum_municipality_kind", 'Aracatu', 'Sudoeste Baiano', '2902005', '33391', NULL),
  ('Araci', 'araci', 'municipio'::"public"."enum_municipality_kind", 'Araci', 'Sisal', '2902104', '33413', NULL),
  ('Aramari', 'aramari', 'municipio'::"public"."enum_municipality_kind", 'Aramari', 'Litoral Norte e Agreste Baiano', '2902203', '33430', NULL),
  ('Arataca', 'arataca', 'municipio'::"public"."enum_municipality_kind", 'Arataca', 'Litoral Sul', '2902252', '30732', NULL),
  ('Aratuípe', 'aratuipe', 'municipio'::"public"."enum_municipality_kind", 'Aratuípe', 'Baixo Sul', '2902302', '33456', NULL),
  ('Aurelino Leal', 'aurelino-leal', 'municipio'::"public"."enum_municipality_kind", 'Aurelino Leal', 'Litoral Sul', '2902401', '33472', NULL),
  ('Baianópolis', 'baianopolis', 'municipio'::"public"."enum_municipality_kind", 'Baianópolis', 'Bacia do Rio Grande', '2902500', '33499', NULL),
  ('Baixa Grande', 'baixa-grande', 'municipio'::"public"."enum_municipality_kind", 'Baixa Grande', 'Bacia do Jacuípe', '2902609', '33510', NULL),
  ('Banzaê', 'banzae', 'municipio'::"public"."enum_municipality_kind", 'Banzaê', 'Semiárido Nordeste II', '2902658', '33529', NULL),
  ('Barra', 'barra', 'municipio'::"public"."enum_municipality_kind", 'Barra', 'Velho Chico', '2902708', '33537', NULL),
  ('Barra da Estiva', 'barra-da-estiva', 'municipio'::"public"."enum_municipality_kind", 'Barra da Estiva', 'Chapada Diamantina', '2902807', '33553', NULL),
  ('Barra do Choça', 'barra-do-choca', 'municipio'::"public"."enum_municipality_kind", 'Barra do Choça', 'Sudoeste Baiano', '2902906', '33570', NULL),
  ('Barra do Mendes', 'barra-do-mendes', 'municipio'::"public"."enum_municipality_kind", 'Barra do Mendes', 'Irecê', '2903003', '33596', NULL),
  ('Barra do Rocha', 'barra-do-rocha', 'municipio'::"public"."enum_municipality_kind", 'Barra do Rocha', 'Médio Rio de Contas', '2903102', '33618', NULL),
  ('Barreiras', 'barreiras', 'municipio'::"public"."enum_municipality_kind", 'Barreiras', 'Bacia do Rio Grande', '2903201', '33634', NULL),
  ('Barro Alto', 'barro-alto', 'municipio'::"public"."enum_municipality_kind", 'Barro Alto', 'Irecê', '2903235', '30759', NULL),
  ('Barro Preto', 'barro-preto', 'municipio'::"public"."enum_municipality_kind", 'Barro Preto', 'Litoral Sul', '2903300', '33650', NULL),
  ('Barrocas', 'barrocas', 'municipio'::"public"."enum_municipality_kind", 'Barrocas', 'Sisal', '2903276', '30775', NULL),
  ('Belmonte', 'belmonte', 'municipio'::"public"."enum_municipality_kind", 'Belmonte', 'Costa do Descobrimento', '2903409', '33677', NULL),
  ('Belo Campo', 'belo-campo', 'municipio'::"public"."enum_municipality_kind", 'Belo Campo', 'Sudoeste Baiano', '2903508', '33693', NULL),
  ('Biritinga', 'biritinga', 'municipio'::"public"."enum_municipality_kind", 'Biritinga', 'Sisal', '2903607', '33715', NULL),
  ('Boa Nova', 'boa-nova', 'municipio'::"public"."enum_municipality_kind", 'Boa Nova', 'Médio Rio de Contas', '2903706', '33731', NULL),
  ('Boa Vista do Tupim', 'boa-vista-do-tupim', 'municipio'::"public"."enum_municipality_kind", 'Boa Vista do Tupim', 'Piemonte do Paraguaçu', '2903805', '33758', NULL),
  ('Bom Jesus da Lapa', 'bom-jesus-da-lapa', 'municipio'::"public"."enum_municipality_kind", 'Bom Jesus da Lapa', 'Velho Chico', '2903904', '33774', NULL),
  ('Bom Jesus da Serra', 'bom-jesus-da-serra', 'municipio'::"public"."enum_municipality_kind", 'Bom Jesus da Serra', 'Sudoeste Baiano', '2903953', '33782', NULL),
  ('Boninal', 'boninal', 'municipio'::"public"."enum_municipality_kind", 'Boninal', 'Chapada Diamantina', '2904001', '33790', NULL),
  ('Bonito', 'bonito', 'municipio'::"public"."enum_municipality_kind", 'Bonito', 'Chapada Diamantina', '2904050', '33804', NULL),
  ('Boquira', 'boquira', 'municipio'::"public"."enum_municipality_kind", 'Boquira', 'Bacia do Paramirim', '2904100', '33812', NULL),
  ('Botuporã', 'botupora', 'municipio'::"public"."enum_municipality_kind", 'Botuporã', 'Bacia do Paramirim', '2904209', '33839', NULL),
  ('Brejões', 'brejoes', 'municipio'::"public"."enum_municipality_kind", 'Brejões', 'Vale do Jiquiriçá', '2904308', '33855', NULL),
  ('Brejolândia', 'brejolandia', 'municipio'::"public"."enum_municipality_kind", 'Brejolândia', 'Bacia do Rio Corrente', '2904407', '33871', NULL),
  ('Brotas de Macaúbas', 'brotas-de-macaubas', 'municipio'::"public"."enum_municipality_kind", 'Brotas de Macaúbas', 'Velho Chico', '2904506', '33898', NULL),
  ('Brumado', 'brumado', 'municipio'::"public"."enum_municipality_kind", 'Brumado', 'Sertão Produtivo', '2904605', '33910', NULL),
  ('Buerarema', 'buerarema', 'municipio'::"public"."enum_municipality_kind", 'Buerarema', 'Litoral Sul', '2904704', '33936', NULL),
  ('Buritirama', 'buritirama', 'municipio'::"public"."enum_municipality_kind", 'Buritirama', 'Bacia do Rio Grande', '2904753', '30791', NULL),
  ('Caatiba', 'caatiba', 'municipio'::"public"."enum_municipality_kind", 'Caatiba', 'Médio Sudoeste da Bahia', '2904803', '33952', NULL),
  ('Cabaceiras do Paraguaçu', 'cabaceiras-do-paraguacu', 'municipio'::"public"."enum_municipality_kind", 'Cabaceiras do Paraguaçu', 'Recôncavo', '2904852', '33960', NULL),
  ('Cachoeira', 'cachoeira', 'municipio'::"public"."enum_municipality_kind", 'Cachoeira', 'Recôncavo', '2904902', '33979', NULL),
  ('Caculé', 'cacule', 'municipio'::"public"."enum_municipality_kind", 'Caculé', 'Sertão Produtivo', '2905008', '33995', NULL),
  ('Caém', 'caem', 'municipio'::"public"."enum_municipality_kind", 'Caém', 'Piemonte da Diamantina', '2905107', '34010', NULL),
  ('Caetanos', 'caetanos', 'municipio'::"public"."enum_municipality_kind", 'Caetanos', 'Sudoeste Baiano', '2905156', '34029', NULL),
  ('Caetité', 'caetite', 'municipio'::"public"."enum_municipality_kind", 'Caetité', 'Sertão Produtivo', '2905206', '34037', NULL),
  ('Cafarnaum', 'cafarnaum', 'municipio'::"public"."enum_municipality_kind", 'Cafarnaum', 'Irecê', '2905305', '34053', NULL),
  ('Cairu', 'cairu', 'municipio'::"public"."enum_municipality_kind", 'Cairu', 'Baixo Sul', '2905404', '34070', NULL),
  ('Caldeirão Grande', 'caldeirao-grande', 'municipio'::"public"."enum_municipality_kind", 'Caldeirão Grande', 'Piemonte Norte do Itapicuru', '2905503', '34096', NULL),
  ('Camacan', 'camacan', 'municipio'::"public"."enum_municipality_kind", 'Camacan', 'Litoral Sul', '2905602', '34118', NULL),
  ('Camaçari', 'camacari', 'municipio'::"public"."enum_municipality_kind", 'Camaçari', 'Metropolitano de Salvador', '2905701', '34134', NULL),
  ('Camamu', 'camamu', 'municipio'::"public"."enum_municipality_kind", 'Camamu', 'Baixo Sul', '2905800', '34150', NULL),
  ('Campo Alegre de Lourdes', 'campo-alegre-de-lourdes', 'municipio'::"public"."enum_municipality_kind", 'Campo Alegre de Lourdes', 'Sertão do São Francisco', '2905909', '34177', NULL),
  ('Campo Formoso', 'campo-formoso', 'municipio'::"public"."enum_municipality_kind", 'Campo Formoso', 'Piemonte Norte do Itapicuru', '2906006', '34193', NULL),
  ('Canápolis', 'canapolis', 'municipio'::"public"."enum_municipality_kind", 'Canápolis', 'Bacia do Rio Corrente', '2906105', '34215', NULL),
  ('Canarana', 'canarana', 'municipio'::"public"."enum_municipality_kind", 'Canarana', 'Irecê', '2906204', '34231', NULL),
  ('Canavieiras', 'canavieiras', 'municipio'::"public"."enum_municipality_kind", 'Canavieiras', 'Litoral Sul', '2906303', '34258', NULL),
  ('Candeal', 'candeal', 'municipio'::"public"."enum_municipality_kind", 'Candeal', 'Sisal', '2906402', '34274', NULL),
  ('Candeias', 'candeias', 'municipio'::"public"."enum_municipality_kind", 'Candeias', 'Metropolitano de Salvador', '2906501', '34290', NULL),
  ('Candiba', 'candiba', 'municipio'::"public"."enum_municipality_kind", 'Candiba', 'Sertão Produtivo', '2906600', '34312', NULL),
  ('Cândido Sales', 'candido-sales', 'municipio'::"public"."enum_municipality_kind", 'Cândido Sales', 'Sudoeste Baiano', '2906709', '34339', NULL),
  ('Cansanção', 'cansancao', 'municipio'::"public"."enum_municipality_kind", 'Cansanção', 'Sisal', '2906808', '34355', NULL),
  ('Canudos', 'canudos', 'municipio'::"public"."enum_municipality_kind", 'Canudos', 'Sertão do São Francisco', '2906824', '30856', NULL),
  ('Capela do Alto Alegre', 'capela-do-alto-alegre', 'municipio'::"public"."enum_municipality_kind", 'Capela do Alto Alegre', 'Bacia do Jacuípe', '2906857', '30813', NULL),
  ('Capim Grosso', 'capim-grosso', 'municipio'::"public"."enum_municipality_kind", 'Capim Grosso', 'Bacia do Jacuípe', '2906873', '30830', NULL),
  ('Caraíbas', 'caraibas', 'municipio'::"public"."enum_municipality_kind", 'Caraíbas', 'Sudoeste Baiano', '2906899', '34363', NULL),
  ('Caravelas', 'caravelas', 'municipio'::"public"."enum_municipality_kind", 'Caravelas', 'Extremo Sul', '2906907', '34371', NULL),
  ('Cardeal da Silva', 'cardeal-da-silva', 'municipio'::"public"."enum_municipality_kind", 'Cardeal da Silva', 'Litoral Norte e Agreste Baiano', '2907004', '34398', NULL),
  ('Carinhanha', 'carinhanha', 'municipio'::"public"."enum_municipality_kind", 'Carinhanha', 'Velho Chico', '2907103', '34410', NULL),
  ('Casa Nova', 'casa-nova', 'municipio'::"public"."enum_municipality_kind", 'Casa Nova', 'Sertão do São Francisco', '2907202', '34436', NULL),
  ('Castro Alves', 'castro-alves', 'municipio'::"public"."enum_municipality_kind", 'Castro Alves', 'Recôncavo', '2907301', '34452', NULL),
  ('Catolândia', 'catolandia', 'municipio'::"public"."enum_municipality_kind", 'Catolândia', 'Bacia do Rio Grande', '2907400', '34479', NULL),
  ('Catu', 'catu', 'municipio'::"public"."enum_municipality_kind", 'Catu', 'Litoral Norte e Agreste Baiano', '2907509', '34495', NULL),
  ('Caturama', 'caturama', 'municipio'::"public"."enum_municipality_kind", 'Caturama', 'Bacia do Paramirim', '2907558', '34509', NULL),
  ('Central', 'central', 'municipio'::"public"."enum_municipality_kind", 'Central', 'Irecê', '2907608', '34517', NULL),
  ('Chorrochó', 'chorrocho', 'municipio'::"public"."enum_municipality_kind", 'Chorrochó', 'Itaparica', '2907707', '34533', NULL),
  ('Cícero Dantas', 'cicero-dantas', 'municipio'::"public"."enum_municipality_kind", 'Cícero Dantas', 'Semiárido Nordeste II', '2907806', '34550', NULL),
  ('Cipó', 'cipo', 'municipio'::"public"."enum_municipality_kind", 'Cipó', 'Semiárido Nordeste II', '2907905', '34576', NULL),
  ('Coaraci', 'coaraci', 'municipio'::"public"."enum_municipality_kind", 'Coaraci', 'Litoral Sul', '2908002', '34592', NULL),
  ('Cocos', 'cocos', 'municipio'::"public"."enum_municipality_kind", 'Cocos', 'Bacia do Rio Corrente', '2908101', '34614', NULL),
  ('Conceição da Feira', 'conceicao-da-feira', 'municipio'::"public"."enum_municipality_kind", 'Conceição da Feira', 'Portal do Sertão', '2908200', '34630', NULL),
  ('Conceição do Almeida', 'conceicao-do-almeida', 'municipio'::"public"."enum_municipality_kind", 'Conceição do Almeida', 'Recôncavo', '2908309', '34657', NULL),
  ('Conceição do Coité', 'conceicao-do-coite', 'municipio'::"public"."enum_municipality_kind", 'Conceição do Coité', 'Sisal', '2908408', '34673', NULL),
  ('Conceição do Jacuípe', 'conceicao-do-jacuipe', 'municipio'::"public"."enum_municipality_kind", 'Conceição do Jacuípe', 'Portal do Sertão', '2908507', '34690', NULL),
  ('Conde', 'conde', 'municipio'::"public"."enum_municipality_kind", 'Conde', 'Litoral Norte e Agreste Baiano', '2908606', '34711', NULL),
  ('Condeúba', 'condeuba', 'municipio'::"public"."enum_municipality_kind", 'Condeúba', 'Sudoeste Baiano', '2908705', '34738', NULL),
  ('Contendas do Sincorá', 'contendas-do-sincora', 'municipio'::"public"."enum_municipality_kind", 'Contendas do Sincorá', 'Sertão Produtivo', '2908804', '34754', NULL),
  ('Coração de Maria', 'coracao-de-maria', 'municipio'::"public"."enum_municipality_kind", 'Coração de Maria', 'Portal do Sertão', '2908903', '34770', NULL),
  ('Cordeiros', 'cordeiros', 'municipio'::"public"."enum_municipality_kind", 'Cordeiros', 'Sudoeste Baiano', '2909000', '34797', NULL),
  ('Coribe', 'coribe', 'municipio'::"public"."enum_municipality_kind", 'Coribe', 'Bacia do Rio Corrente', '2909109', '34819', NULL),
  ('Coronel João Sá', 'coronel-joao-sa', 'municipio'::"public"."enum_municipality_kind", 'Coronel João Sá', 'Semiárido Nordeste II', '2909208', '34835', NULL),
  ('Correntina', 'correntina', 'municipio'::"public"."enum_municipality_kind", 'Correntina', 'Bacia do Rio Corrente', '2909307', '34851', NULL),
  ('Cotegipe', 'cotegipe', 'municipio'::"public"."enum_municipality_kind", 'Cotegipe', 'Bacia do Rio Grande', '2909406', '34878', NULL),
  ('Cravolândia', 'cravolandia', 'municipio'::"public"."enum_municipality_kind", 'Cravolândia', 'Vale do Jiquiriçá', '2909505', '34894', NULL),
  ('Crisópolis', 'crisopolis', 'municipio'::"public"."enum_municipality_kind", 'Crisópolis', 'Litoral Norte e Agreste Baiano', '2909604', '34916', NULL),
  ('Cristópolis', 'cristopolis', 'municipio'::"public"."enum_municipality_kind", 'Cristópolis', 'Bacia do Rio Grande', '2909703', '34932', NULL),
  ('Cruz das Almas', 'cruz-das-almas', 'municipio'::"public"."enum_municipality_kind", 'Cruz das Almas', 'Recôncavo', '2909802', '34959', NULL),
  ('Curaçá', 'curaca', 'municipio'::"public"."enum_municipality_kind", 'Curaçá', 'Sertão do São Francisco', '2909901', '34975', NULL),
  ('Dário Meira', 'dario-meira', 'municipio'::"public"."enum_municipality_kind", 'Dário Meira', 'Médio Rio de Contas', '2910008', '34991', NULL),
  ('Dias d''Ávila', 'dias-d-avila', 'municipio'::"public"."enum_municipality_kind", 'Dias d''Ávila', 'Metropolitano de Salvador', '2910057', '30872', NULL),
  ('Dom Basílio', 'dom-basilio', 'municipio'::"public"."enum_municipality_kind", 'Dom Basílio', 'Sertão Produtivo', '2910107', '35017', NULL),
  ('Dom Macedo Costa', 'dom-macedo-costa', 'municipio'::"public"."enum_municipality_kind", 'Dom Macedo Costa', 'Recôncavo', '2910206', '35033', NULL),
  ('Elísio Medrado', 'elisio-medrado', 'municipio'::"public"."enum_municipality_kind", 'Elísio Medrado', 'Vale do Jiquiriçá', '2910305', '35050', NULL),
  ('Encruzilhada', 'encruzilhada', 'municipio'::"public"."enum_municipality_kind", 'Encruzilhada', 'Sudoeste Baiano', '2910404', '35076', NULL),
  ('Entre Rios', 'entre-rios', 'municipio'::"public"."enum_municipality_kind", 'Entre Rios', 'Litoral Norte e Agreste Baiano', '2910503', '35092', NULL),
  ('Érico Cardoso', 'erico-cardoso', 'municipio'::"public"."enum_municipality_kind", 'Érico Cardoso', 'Bacia do Paramirim', '2900504', '33090', NULL),
  ('Esplanada', 'esplanada', 'municipio'::"public"."enum_municipality_kind", 'Esplanada', 'Litoral Norte e Agreste Baiano', '2910602', '35114', NULL),
  ('Euclides da Cunha', 'euclides-da-cunha', 'municipio'::"public"."enum_municipality_kind", 'Euclides da Cunha', 'Semiárido Nordeste II', '2910701', '35130', NULL),
  ('Eunápolis', 'eunapolis', 'municipio'::"public"."enum_municipality_kind", 'Eunápolis', 'Costa do Descobrimento', '2910727', '30058', NULL),
  ('Fátima', 'fatima', 'municipio'::"public"."enum_municipality_kind", 'Fátima', 'Semiárido Nordeste II', '2910750', '30899', NULL),
  ('Feira da Mata', 'feira-da-mata', 'municipio'::"public"."enum_municipality_kind", 'Feira da Mata', 'Velho Chico', '2910776', '35149', NULL),
  ('Feira de Santana', 'feira-de-santana', 'municipio'::"public"."enum_municipality_kind", 'Feira de Santana', 'Portal do Sertão', '2910800', '35157', NULL),
  ('Filadélfia', 'filadelfia', 'municipio'::"public"."enum_municipality_kind", 'Filadélfia', 'Piemonte Norte do Itapicuru', '2910859', '30910', NULL),
  ('Firmino Alves', 'firmino-alves', 'municipio'::"public"."enum_municipality_kind", 'Firmino Alves', 'Médio Sudoeste da Bahia', '2910909', '35173', NULL),
  ('Floresta Azul', 'floresta-azul', 'municipio'::"public"."enum_municipality_kind", 'Floresta Azul', 'Litoral Sul', '2911006', '35190', NULL),
  ('Formosa do Rio Preto', 'formosa-do-rio-preto', 'municipio'::"public"."enum_municipality_kind", 'Formosa do Rio Preto', 'Bacia do Rio Grande', '2911105', '35211', NULL),
  ('Gandu', 'gandu', 'municipio'::"public"."enum_municipality_kind", 'Gandu', 'Baixo Sul', '2911204', '35238', NULL),
  ('Gavião', 'gaviao', 'municipio'::"public"."enum_municipality_kind", 'Gavião', 'Bacia do Jacuípe', '2911253', '30937', NULL),
  ('Gentio do Ouro', 'gentio-do-ouro', 'municipio'::"public"."enum_municipality_kind", 'Gentio do Ouro', 'Irecê', '2911303', '35254', NULL),
  ('Glória', 'gloria', 'municipio'::"public"."enum_municipality_kind", 'Glória', 'Itaparica', '2911402', '35270', NULL),
  ('Gongogi', 'gongogi', 'municipio'::"public"."enum_municipality_kind", 'Gongogi', 'Médio Rio de Contas', '2911501', '35297', NULL),
  ('Governador Mangabeira', 'governador-mangabeira', 'municipio'::"public"."enum_municipality_kind", 'Governador Mangabeira', 'Recôncavo', '2911600', '35319', NULL),
  ('Guajeru', 'guajeru', 'municipio'::"public"."enum_municipality_kind", 'Guajeru', 'Sudoeste Baiano', '2911659', '30953', NULL),
  ('Guanambi', 'guanambi', 'municipio'::"public"."enum_municipality_kind", 'Guanambi', 'Sertão Produtivo', '2911709', '35335', NULL),
  ('Guaratinga', 'guaratinga', 'municipio'::"public"."enum_municipality_kind", 'Guaratinga', 'Costa do Descobrimento', '2911808', '35351', NULL),
  ('Heliópolis', 'heliopolis', 'municipio'::"public"."enum_municipality_kind", 'Heliópolis', 'Semiárido Nordeste II', '2911857', '30970', NULL),
  ('Iaçu', 'iacu', 'municipio'::"public"."enum_municipality_kind", 'Iaçu', 'Piemonte do Paraguaçu', '2911907', '35378', NULL),
  ('Ibiassucê', 'ibiassuce', 'municipio'::"public"."enum_municipality_kind", 'Ibiassucê', 'Sertão Produtivo', '2912004', '35394', NULL),
  ('Ibicaraí', 'ibicarai', 'municipio'::"public"."enum_municipality_kind", 'Ibicaraí', 'Litoral Sul', '2912103', '35416', NULL),
  ('Ibicoara', 'ibicoara', 'municipio'::"public"."enum_municipality_kind", 'Ibicoara', 'Chapada Diamantina', '2912202', '35432', NULL),
  ('Ibicuí', 'ibicui', 'municipio'::"public"."enum_municipality_kind", 'Ibicuí', 'Médio Sudoeste da Bahia', '2912301', '35459', NULL),
  ('Ibipeba', 'ibipeba', 'municipio'::"public"."enum_municipality_kind", 'Ibipeba', 'Irecê', '2912400', '35475', NULL),
  ('Ibipitanga', 'ibipitanga', 'municipio'::"public"."enum_municipality_kind", 'Ibipitanga', 'Bacia do Paramirim', '2912509', '35513', NULL),
  ('Ibiquera', 'ibiquera', 'municipio'::"public"."enum_municipality_kind", 'Ibiquera', 'Piemonte do Paraguaçu', '2912608', '35530', NULL),
  ('Ibirapitanga', 'ibirapitanga', 'municipio'::"public"."enum_municipality_kind", 'Ibirapitanga', 'Baixo Sul', '2912707', '35556', NULL),
  ('Ibirapuã', 'ibirapua', 'municipio'::"public"."enum_municipality_kind", 'Ibirapuã', 'Extremo Sul', '2912806', '35572', NULL),
  ('Ibirataia', 'ibirataia', 'municipio'::"public"."enum_municipality_kind", 'Ibirataia', 'Médio Rio de Contas', '2912905', '35599', NULL),
  ('Ibitiara', 'ibitiara', 'municipio'::"public"."enum_municipality_kind", 'Ibitiara', 'Chapada Diamantina', '2913002', '35610', NULL),
  ('Ibititá', 'ibitita', 'municipio'::"public"."enum_municipality_kind", 'Ibititá', 'Irecê', '2913101', '35637', NULL),
  ('Ibotirama', 'ibotirama', 'municipio'::"public"."enum_municipality_kind", 'Ibotirama', 'Velho Chico', '2913200', '35653', NULL),
  ('Ichu', 'ichu', 'municipio'::"public"."enum_municipality_kind", 'Ichu', 'Sisal', '2913309', '35670', NULL),
  ('Igaporã', 'igapora', 'municipio'::"public"."enum_municipality_kind", 'Igaporã', 'Velho Chico', '2913408', '35696', NULL),
  ('Igrapiúna', 'igrapiuna', 'municipio'::"public"."enum_municipality_kind", 'Igrapiúna', 'Baixo Sul', '2913457', '35700', NULL),
  ('Iguaí', 'iguai', 'municipio'::"public"."enum_municipality_kind", 'Iguaí', 'Médio Sudoeste da Bahia', '2913507', '35718', NULL),
  ('Ilhéus', 'ilheus', 'municipio'::"public"."enum_municipality_kind", 'Ilhéus', 'Litoral Sul', '2913606', '35734', NULL),
  ('Inhambupe', 'inhambupe', 'municipio'::"public"."enum_municipality_kind", 'Inhambupe', 'Litoral Norte e Agreste Baiano', '2913705', '35750', NULL),
  ('Ipecaetá', 'ipecaeta', 'municipio'::"public"."enum_municipality_kind", 'Ipecaetá', 'Portal do Sertão', '2913804', '35777', NULL),
  ('Ipiaú', 'ipiau', 'municipio'::"public"."enum_municipality_kind", 'Ipiaú', 'Médio Rio de Contas', '2913903', '35793', NULL),
  ('Ipirá', 'ipira', 'municipio'::"public"."enum_municipality_kind", 'Ipirá', 'Bacia do Jacuípe', '2914000', '35815', NULL),
  ('Ipupiara', 'ipupiara', 'municipio'::"public"."enum_municipality_kind", 'Ipupiara', 'Irecê', '2914109', '35831', NULL),
  ('Irajuba', 'irajuba', 'municipio'::"public"."enum_municipality_kind", 'Irajuba', 'Vale do Jiquiriçá', '2914208', '35858', NULL),
  ('Iramaia', 'iramaia', 'municipio'::"public"."enum_municipality_kind", 'Iramaia', 'Chapada Diamantina', '2914307', '35874', NULL),
  ('Iraquara', 'iraquara', 'municipio'::"public"."enum_municipality_kind", 'Iraquara', 'Chapada Diamantina', '2914406', '35890', NULL),
  ('Irará', 'irara', 'municipio'::"public"."enum_municipality_kind", 'Irará', 'Portal do Sertão', '2914505', '35912', NULL),
  ('Irecê', 'irece', 'municipio'::"public"."enum_municipality_kind", 'Irecê', 'Irecê', '2914604', '35939', NULL),
  ('Itabela', 'itabela', 'municipio'::"public"."enum_municipality_kind", 'Itabela', 'Costa do Descobrimento', '2914653', '35947', NULL),
  ('Itaberaba', 'itaberaba', 'municipio'::"public"."enum_municipality_kind", 'Itaberaba', 'Piemonte do Paraguaçu', '2914703', '35955', NULL),
  ('Itabuna', 'itabuna', 'municipio'::"public"."enum_municipality_kind", 'Itabuna', 'Litoral Sul', '2914802', '35971', NULL),
  ('Itacaré', 'itacare', 'municipio'::"public"."enum_municipality_kind", 'Itacaré', 'Litoral Sul', '2914901', '35998', NULL),
  ('Itaeté', 'itaete', 'municipio'::"public"."enum_municipality_kind", 'Itaeté', 'Chapada Diamantina', '2915007', '36013', NULL),
  ('Itagi', 'itagi', 'municipio'::"public"."enum_municipality_kind", 'Itagi', 'Médio Rio de Contas', '2915106', '36030', NULL),
  ('Itagibá', 'itagiba', 'municipio'::"public"."enum_municipality_kind", 'Itagibá', 'Médio Rio de Contas', '2915205', '36056', NULL),
  ('Itagimirim', 'itagimirim', 'municipio'::"public"."enum_municipality_kind", 'Itagimirim', 'Costa do Descobrimento', '2915304', '36072', NULL),
  ('Itaguaçu da Bahia', 'itaguacu-da-bahia', 'municipio'::"public"."enum_municipality_kind", 'Itaguaçu da Bahia', 'Irecê', '2915353', '36080', NULL),
  ('Itaju do Colônia', 'itaju-do-colonia', 'municipio'::"public"."enum_municipality_kind", 'Itaju do Colônia', 'Litoral Sul', '2915403', '36099', NULL),
  ('Itajuípe', 'itajuipe', 'municipio'::"public"."enum_municipality_kind", 'Itajuípe', 'Litoral Sul', '2915502', '36110', NULL),
  ('Itamaraju', 'itamaraju', 'municipio'::"public"."enum_municipality_kind", 'Itamaraju', 'Extremo Sul', '2915601', '36137', NULL),
  ('Itamari', 'itamari', 'municipio'::"public"."enum_municipality_kind", 'Itamari', 'Médio Rio de Contas', '2915700', '36153', NULL),
  ('Itambé', 'itambe', 'municipio'::"public"."enum_municipality_kind", 'Itambé', 'Médio Sudoeste da Bahia', '2915809', '36170', NULL),
  ('Itanagra', 'itanagra', 'municipio'::"public"."enum_municipality_kind", 'Itanagra', 'Litoral Norte e Agreste Baiano', '2915908', '36196', NULL),
  ('Itanhém', 'itanhem', 'municipio'::"public"."enum_municipality_kind", 'Itanhém', 'Extremo Sul', '2916005', '36218', NULL),
  ('Itaparica', 'itaparica', 'municipio'::"public"."enum_municipality_kind", 'Itaparica', 'Metropolitano de Salvador', '2916104', '36234', NULL),
  ('Itapé', 'itape', 'municipio'::"public"."enum_municipality_kind", 'Itapé', 'Litoral Sul', '2916203', '36250', NULL),
  ('Itapebi', 'itapebi', 'municipio'::"public"."enum_municipality_kind", 'Itapebi', 'Costa do Descobrimento', '2916302', '36277', NULL),
  ('Itapetinga', 'itapetinga', 'municipio'::"public"."enum_municipality_kind", 'Itapetinga', 'Médio Sudoeste da Bahia', '2916401', '36293', NULL),
  ('Itapicuru', 'itapicuru', 'municipio'::"public"."enum_municipality_kind", 'Itapicuru', 'Litoral Norte e Agreste Baiano', '2916500', '36315', NULL),
  ('Itapitanga', 'itapitanga', 'municipio'::"public"."enum_municipality_kind", 'Itapitanga', 'Litoral Sul', '2916609', '36331', NULL),
  ('Itaquara', 'itaquara', 'municipio'::"public"."enum_municipality_kind", 'Itaquara', 'Vale do Jiquiriçá', '2916708', '36358', NULL),
  ('Itarantim', 'itarantim', 'municipio'::"public"."enum_municipality_kind", 'Itarantim', 'Médio Sudoeste da Bahia', '2916807', '36374', NULL),
  ('Itatim', 'itatim', 'municipio'::"public"."enum_municipality_kind", 'Itatim', 'Piemonte do Paraguaçu', '2916856', '36382', NULL),
  ('Itiruçu', 'itirucu', 'municipio'::"public"."enum_municipality_kind", 'Itiruçu', 'Vale do Jiquiriçá', '2916906', '36390', NULL),
  ('Itiúba', 'itiuba', 'municipio'::"public"."enum_municipality_kind", 'Itiúba', 'Sisal', '2917003', '36412', NULL),
  ('Itororó', 'itororo', 'municipio'::"public"."enum_municipality_kind", 'Itororó', 'Médio Sudoeste da Bahia', '2917102', '36439', NULL),
  ('Ituaçu', 'ituacu', 'municipio'::"public"."enum_municipality_kind", 'Ituaçu', 'Sertão Produtivo', '2917201', '36455', NULL),
  ('Ituberá', 'itubera', 'municipio'::"public"."enum_municipality_kind", 'Ituberá', 'Baixo Sul', '2917300', '36471', NULL),
  ('Iuiú', 'iuiu', 'municipio'::"public"."enum_municipality_kind", 'Iuiú', 'Sertão Produtivo', '2917334', '30660', NULL),
  ('Jaborandi', 'jaborandi', 'municipio'::"public"."enum_municipality_kind", 'Jaborandi', 'Bacia do Rio Corrente', '2917359', '30678', NULL),
  ('Jacaraci', 'jacaraci', 'municipio'::"public"."enum_municipality_kind", 'Jacaraci', 'Sudoeste Baiano', '2917409', '36498', NULL),
  ('Jacobina', 'jacobina', 'municipio'::"public"."enum_municipality_kind", 'Jacobina', 'Piemonte da Diamantina', '2917508', '36510', NULL),
  ('Jaguaquara', 'jaguaquara', 'municipio'::"public"."enum_municipality_kind", 'Jaguaquara', 'Vale do Jiquiriçá', '2917607', '36536', NULL),
  ('Jaguarari', 'jaguarari', 'municipio'::"public"."enum_municipality_kind", 'Jaguarari', 'Piemonte Norte do Itapicuru', '2917706', '36552', NULL),
  ('Jaguaripe', 'jaguaripe', 'municipio'::"public"."enum_municipality_kind", 'Jaguaripe', 'Baixo Sul', '2917805', '36579', NULL),
  ('Jandaíra', 'jandaira', 'municipio'::"public"."enum_municipality_kind", 'Jandaíra', 'Litoral Norte e Agreste Baiano', '2917904', '36595', NULL),
  ('Jequié', 'jequie', 'municipio'::"public"."enum_municipality_kind", 'Jequié', 'Médio Rio de Contas', '2918001', '36617', NULL),
  ('Jeremoabo', 'jeremoabo', 'municipio'::"public"."enum_municipality_kind", 'Jeremoabo', 'Semiárido Nordeste II', '2918100', '36633', NULL),
  ('Jiquiriçá', 'jiquirica', 'municipio'::"public"."enum_municipality_kind", 'Jiquiriçá', 'Vale do Jiquiriçá', '2918209', '36650', NULL),
  ('Jitaúna', 'jitauna', 'municipio'::"public"."enum_municipality_kind", 'Jitaúna', 'Médio Rio de Contas', '2918308', '36676', NULL),
  ('João Dourado', 'joao-dourado', 'municipio'::"public"."enum_municipality_kind", 'João Dourado', 'Irecê', '2918357', '30996', NULL),
  ('Juazeiro', 'juazeiro', 'municipio'::"public"."enum_municipality_kind", 'Juazeiro', 'Sertão do São Francisco', '2918407', '36692', NULL),
  ('Jucuruçu', 'jucurucu', 'municipio'::"public"."enum_municipality_kind", 'Jucuruçu', 'Extremo Sul', '2918456', '36706', NULL),
  ('Jussara', 'jussara', 'municipio'::"public"."enum_municipality_kind", 'Jussara', 'Irecê', '2918506', '36714', NULL),
  ('Jussari', 'jussari', 'municipio'::"public"."enum_municipality_kind", 'Jussari', 'Litoral Sul', '2918555', '30694', NULL),
  ('Jussiape', 'jussiape', 'municipio'::"public"."enum_municipality_kind", 'Jussiape', 'Chapada Diamantina', '2918605', '36730', NULL),
  ('Lafaiete Coutinho', 'lafaiete-coutinho', 'municipio'::"public"."enum_municipality_kind", 'Lafaiete Coutinho', 'Vale do Jiquiriçá', '2918704', '36757', NULL),
  ('Lagoa Real', 'lagoa-real', 'municipio'::"public"."enum_municipality_kind", 'Lagoa Real', 'Sertão Produtivo', '2918753', '36765', NULL),
  ('Laje', 'laje', 'municipio'::"public"."enum_municipality_kind", 'Laje', 'Vale do Jiquiriçá', '2918803', '36773', NULL),
  ('Lajedão', 'lajedao', 'municipio'::"public"."enum_municipality_kind", 'Lajedão', 'Extremo Sul', '2918902', '36790', NULL),
  ('Lajedinho', 'lajedinho', 'municipio'::"public"."enum_municipality_kind", 'Lajedinho', 'Piemonte do Paraguaçu', '2919009', '36811', NULL),
  ('Lajedo do Tabocal', 'lajedo-do-tabocal', 'municipio'::"public"."enum_municipality_kind", 'Lajedo do Tabocal', 'Vale do Jiquiriçá', '2919058', '36820', NULL),
  ('Lamarão', 'lamarao', 'municipio'::"public"."enum_municipality_kind", 'Lamarão', 'Sisal', '2919108', '36838', NULL),
  ('Lapão', 'lapao', 'municipio'::"public"."enum_municipality_kind", 'Lapão', 'Irecê', '2919157', '39730', NULL),
  ('Lauro de Freitas', 'lauro-de-freitas', 'municipio'::"public"."enum_municipality_kind", 'Lauro de Freitas', 'Metropolitano de Salvador', '2919207', '36854', NULL),
  ('Lençóis', 'lencois', 'municipio'::"public"."enum_municipality_kind", 'Lençóis', 'Chapada Diamantina', '2919306', '36870', NULL),
  ('Licínio de Almeida', 'licinio-de-almeida', 'municipio'::"public"."enum_municipality_kind", 'Licínio de Almeida', 'Sudoeste Baiano', '2919405', '36897', NULL),
  ('Livramento de Nossa Senhora', 'livramento-de-nossa-senhora', 'municipio'::"public"."enum_municipality_kind", 'Livramento de Nossa Senhora', 'Sertão Produtivo', '2919504', '36919', NULL),
  ('Luís Eduardo Magalhães', 'luis-eduardo-magalhaes', 'municipio'::"public"."enum_municipality_kind", 'Luís Eduardo Magalhães', 'Bacia do Rio Grande', '2919553', '30007', NULL),
  ('Macajuba', 'macajuba', 'municipio'::"public"."enum_municipality_kind", 'Macajuba', 'Piemonte do Paraguaçu', '2919603', '36935', NULL),
  ('Macarani', 'macarani', 'municipio'::"public"."enum_municipality_kind", 'Macarani', 'Médio Sudoeste da Bahia', '2919702', '36951', NULL),
  ('Macaúbas', 'macaubas', 'municipio'::"public"."enum_municipality_kind", 'Macaúbas', 'Bacia do Paramirim', '2919801', '36978', NULL),
  ('Macururé', 'macurure', 'municipio'::"public"."enum_municipality_kind", 'Macururé', 'Itaparica', '2919900', '36994', NULL),
  ('Madre de Deus', 'madre-de-deus', 'municipio'::"public"."enum_municipality_kind", 'Madre de Deus', 'Metropolitano de Salvador', '2919926', '39748', NULL),
  ('Maetinga', 'maetinga', 'municipio'::"public"."enum_municipality_kind", 'Maetinga', 'Sudoeste Baiano', '2919959', '39756', NULL),
  ('Maiquinique', 'maiquinique', 'municipio'::"public"."enum_municipality_kind", 'Maiquinique', 'Médio Sudoeste da Bahia', '2920007', '37010', NULL),
  ('Mairi', 'mairi', 'municipio'::"public"."enum_municipality_kind", 'Mairi', 'Bacia do Jacuípe', '2920106', '37036', NULL),
  ('Malhada', 'malhada', 'municipio'::"public"."enum_municipality_kind", 'Malhada', 'Velho Chico', '2920205', '37052', NULL),
  ('Malhada de Pedras', 'malhada-de-pedras', 'municipio'::"public"."enum_municipality_kind", 'Malhada de Pedras', 'Sertão Produtivo', '2920304', '37079', NULL),
  ('Manoel Vitorino', 'manoel-vitorino', 'municipio'::"public"."enum_municipality_kind", 'Manoel Vitorino', 'Médio Rio de Contas', '2920403', '37095', NULL),
  ('Mansidão', 'mansidao', 'municipio'::"public"."enum_municipality_kind", 'Mansidão', 'Bacia do Rio Grande', '2920452', '39772', NULL),
  ('Maracás', 'maracas', 'municipio'::"public"."enum_municipality_kind", 'Maracás', 'Vale do Jiquiriçá', '2920502', '37117', NULL),
  ('Maragogipe', 'maragogipe', 'municipio'::"public"."enum_municipality_kind", 'Maragogipe', 'Recôncavo', '2920601', '37133', NULL),
  ('Maraú', 'marau', 'municipio'::"public"."enum_municipality_kind", 'Maraú', 'Litoral Sul', '2920700', '37150', NULL),
  ('Marcionílio Souza', 'marcionilio-souza', 'municipio'::"public"."enum_municipality_kind", 'Marcionílio Souza', 'Chapada Diamantina', '2920809', '37176', NULL),
  ('Mascote', 'mascote', 'municipio'::"public"."enum_municipality_kind", 'Mascote', 'Litoral Sul', '2920908', '37192', NULL),
  ('Mata de São João', 'mata-de-sao-joao', 'municipio'::"public"."enum_municipality_kind", 'Mata de São João', 'Metropolitano de Salvador', '2921005', '37214', NULL),
  ('Matina', 'matina', 'municipio'::"public"."enum_municipality_kind", 'Matina', 'Velho Chico', '2921054', '37222', NULL),
  ('Medeiros Neto', 'medeiros-neto', 'municipio'::"public"."enum_municipality_kind", 'Medeiros Neto', 'Extremo Sul', '2921104', '37230', NULL),
  ('Miguel Calmon', 'miguel-calmon', 'municipio'::"public"."enum_municipality_kind", 'Miguel Calmon', 'Piemonte da Diamantina', '2921203', '37257', NULL),
  ('Milagres', 'milagres', 'municipio'::"public"."enum_municipality_kind", 'Milagres', 'Vale do Jiquiriçá', '2921302', '37273', NULL),
  ('Mirangaba', 'mirangaba', 'municipio'::"public"."enum_municipality_kind", 'Mirangaba', 'Piemonte da Diamantina', '2921401', '37290', NULL),
  ('Mirante', 'mirante', 'municipio'::"public"."enum_municipality_kind", 'Mirante', 'Sudoeste Baiano', '2921450', '37303', NULL),
  ('Monte Santo', 'monte-santo', 'municipio'::"public"."enum_municipality_kind", 'Monte Santo', 'Sisal', '2921500', '37311', NULL),
  ('Morpará', 'morpara', 'municipio'::"public"."enum_municipality_kind", 'Morpará', 'Velho Chico', '2921609', '37338', NULL),
  ('Morro do Chapéu', 'morro-do-chapeu', 'municipio'::"public"."enum_municipality_kind", 'Morro do Chapéu', 'Chapada Diamantina', '2921708', '37354', NULL),
  ('Mortugaba', 'mortugaba', 'municipio'::"public"."enum_municipality_kind", 'Mortugaba', 'Sudoeste Baiano', '2921807', '37370', NULL),
  ('Mucugê', 'mucuge', 'municipio'::"public"."enum_municipality_kind", 'Mucugê', 'Chapada Diamantina', '2921906', '37397', NULL),
  ('Mucuri', 'mucuri', 'municipio'::"public"."enum_municipality_kind", 'Mucuri', 'Extremo Sul', '2922003', '37419', NULL),
  ('Mulungu do Morro', 'mulungu-do-morro', 'municipio'::"public"."enum_municipality_kind", 'Mulungu do Morro', 'Irecê', '2922052', '37427', NULL),
  ('Mundo Novo', 'mundo-novo', 'municipio'::"public"."enum_municipality_kind", 'Mundo Novo', 'Piemonte do Paraguaçu', '2922102', '37435', NULL),
  ('Muniz Ferreira', 'muniz-ferreira', 'municipio'::"public"."enum_municipality_kind", 'Muniz Ferreira', 'Recôncavo', '2922201', '37451', NULL),
  ('Muquém de São Francisco', 'muquem-de-sao-francisco', 'municipio'::"public"."enum_municipality_kind", 'Muquém de São Francisco', 'Velho Chico', '2922250', '37460', NULL),
  ('Muritiba', 'muritiba', 'municipio'::"public"."enum_municipality_kind", 'Muritiba', 'Recôncavo', '2922300', '37478', NULL),
  ('Mutuípe', 'mutuipe', 'municipio'::"public"."enum_municipality_kind", 'Mutuípe', 'Vale do Jiquiriçá', '2922409', '37494', NULL),
  ('Nazaré', 'nazare', 'municipio'::"public"."enum_municipality_kind", 'Nazaré', 'Recôncavo', '2922508', '37516', NULL),
  ('Nilo Peçanha', 'nilo-pecanha', 'municipio'::"public"."enum_municipality_kind", 'Nilo Peçanha', 'Baixo Sul', '2922607', '37532', NULL),
  ('Nordestina', 'nordestina', 'municipio'::"public"."enum_municipality_kind", 'Nordestina', 'Sisal', '2922656', '39799', NULL),
  ('Nova Canaã', 'nova-canaa', 'municipio'::"public"."enum_municipality_kind", 'Nova Canaã', 'Médio Sudoeste da Bahia', '2922706', '37559', NULL),
  ('Nova Fátima', 'nova-fatima', 'municipio'::"public"."enum_municipality_kind", 'Nova Fátima', 'Bacia do Jacuípe', '2922730', '37567', NULL),
  ('Nova Ibiá', 'nova-ibia', 'municipio'::"public"."enum_municipality_kind", 'Nova Ibiá', 'Médio Rio de Contas', '2922755', '39969', NULL),
  ('Nova Itarana', 'nova-itarana', 'municipio'::"public"."enum_municipality_kind", 'Nova Itarana', 'Vale do Jiquiriçá', '2922805', '37575', NULL),
  ('Nova Redenção', 'nova-redencao', 'municipio'::"public"."enum_municipality_kind", 'Nova Redenção', 'Chapada Diamantina', '2922854', '37583', NULL),
  ('Nova Soure', 'nova-soure', 'municipio'::"public"."enum_municipality_kind", 'Nova Soure', 'Semiárido Nordeste II', '2922904', '37591', NULL),
  ('Nova Viçosa', 'nova-vicosa', 'municipio'::"public"."enum_municipality_kind", 'Nova Viçosa', 'Extremo Sul', '2923001', '37613', NULL),
  ('Novo Horizonte', 'novo-horizonte', 'municipio'::"public"."enum_municipality_kind", 'Novo Horizonte', 'Chapada Diamantina', '2923035', '39942', NULL),
  ('Novo Triunfo', 'novo-triunfo', 'municipio'::"public"."enum_municipality_kind", 'Novo Triunfo', 'Semiárido Nordeste II', '2923050', '37621', NULL),
  ('Olindina', 'olindina', 'municipio'::"public"."enum_municipality_kind", 'Olindina', 'Litoral Norte e Agreste Baiano', '2923100', '37630', NULL),
  ('Oliveira dos Brejinhos', 'oliveira-dos-brejinhos', 'municipio'::"public"."enum_municipality_kind", 'Oliveira dos Brejinhos', 'Velho Chico', '2923209', '37656', NULL),
  ('Ouriçangas', 'ouricangas', 'municipio'::"public"."enum_municipality_kind", 'Ouriçangas', 'Litoral Norte e Agreste Baiano', '2923308', '37672', NULL),
  ('Ourolândia', 'ourolandia', 'municipio'::"public"."enum_municipality_kind", 'Ourolândia', 'Piemonte da Diamantina', '2923357', '37680', NULL),
  ('Palmas de Monte Alto', 'palmas-de-monte-alto', 'municipio'::"public"."enum_municipality_kind", 'Palmas de Monte Alto', 'Sertão Produtivo', '2923407', '37699', NULL),
  ('Palmeiras', 'palmeiras', 'municipio'::"public"."enum_municipality_kind", 'Palmeiras', 'Chapada Diamantina', '2923506', '37710', NULL),
  ('Paramirim', 'paramirim', 'municipio'::"public"."enum_municipality_kind", 'Paramirim', 'Bacia do Paramirim', '2923605', '37737', NULL),
  ('Paratinga', 'paratinga', 'municipio'::"public"."enum_municipality_kind", 'Paratinga', 'Velho Chico', '2923704', '37753', NULL),
  ('Paripiranga', 'paripiranga', 'municipio'::"public"."enum_municipality_kind", 'Paripiranga', 'Semiárido Nordeste II', '2923803', '37770', NULL),
  ('Pau Brasil', 'pau-brasil', 'municipio'::"public"."enum_municipality_kind", 'Pau Brasil', 'Litoral Sul', '2923902', '37796', NULL),
  ('Paulo Afonso', 'paulo-afonso', 'municipio'::"public"."enum_municipality_kind", 'Paulo Afonso', 'Itaparica', '2924009', '37818', NULL),
  ('Pé de Serra', 'pe-de-serra', 'municipio'::"public"."enum_municipality_kind", 'Pé de Serra', 'Bacia do Jacuípe', '2924058', '39810', NULL),
  ('Pedrão', 'pedrao', 'municipio'::"public"."enum_municipality_kind", 'Pedrão', 'Litoral Norte e Agreste Baiano', '2924108', '37834', NULL),
  ('Pedro Alexandre', 'pedro-alexandre', 'municipio'::"public"."enum_municipality_kind", 'Pedro Alexandre', 'Semiárido Nordeste II', '2924207', '37850', NULL),
  ('Piatã', 'piata', 'municipio'::"public"."enum_municipality_kind", 'Piatã', 'Chapada Diamantina', '2924306', '37877', NULL),
  ('Pilão Arcado', 'pilao-arcado', 'municipio'::"public"."enum_municipality_kind", 'Pilão Arcado', 'Sertão do São Francisco', '2924405', '37893', NULL),
  ('Pindaí', 'pindai', 'municipio'::"public"."enum_municipality_kind", 'Pindaí', 'Sertão Produtivo', '2924504', '37915', NULL),
  ('Pindobaçu', 'pindobacu', 'municipio'::"public"."enum_municipality_kind", 'Pindobaçu', 'Piemonte Norte do Itapicuru', '2924603', '37931', NULL),
  ('Pintadas', 'pintadas', 'municipio'::"public"."enum_municipality_kind", 'Pintadas', 'Bacia do Jacuípe', '2924652', '39837', NULL),
  ('Piraí do Norte', 'pirai-do-norte', 'municipio'::"public"."enum_municipality_kind", 'Piraí do Norte', 'Baixo Sul', '2924678', '37940', NULL),
  ('Piripá', 'piripa', 'municipio'::"public"."enum_municipality_kind", 'Piripá', 'Sudoeste Baiano', '2924702', '37958', NULL),
  ('Piritiba', 'piritiba', 'municipio'::"public"."enum_municipality_kind", 'Piritiba', 'Piemonte do Paraguaçu', '2924801', '37974', NULL),
  ('Planaltino', 'planaltino', 'municipio'::"public"."enum_municipality_kind", 'Planaltino', 'Vale do Jiquiriçá', '2924900', '37990', NULL),
  ('Planalto', 'planalto', 'municipio'::"public"."enum_municipality_kind", 'Planalto', 'Sudoeste Baiano', '2925006', '38016', NULL),
  ('Poções', 'pocoes', 'municipio'::"public"."enum_municipality_kind", 'Poções', 'Sudoeste Baiano', '2925105', '38032', NULL),
  ('Pojuca', 'pojuca', 'municipio'::"public"."enum_municipality_kind", 'Pojuca', 'Metropolitano de Salvador', '2925204', '38059', NULL),
  ('Ponto Novo', 'ponto-novo', 'municipio'::"public"."enum_municipality_kind", 'Ponto Novo', 'Piemonte Norte do Itapicuru', '2925253', '38067', NULL),
  ('Porto Seguro', 'porto-seguro', 'municipio'::"public"."enum_municipality_kind", 'Porto Seguro', 'Costa do Descobrimento', '2925303', '38075', NULL),
  ('Potiraguá', 'potiragua', 'municipio'::"public"."enum_municipality_kind", 'Potiraguá', 'Médio Sudoeste da Bahia', '2925402', '38091', NULL),
  ('Prado', 'prado', 'municipio'::"public"."enum_municipality_kind", 'Prado', 'Extremo Sul', '2925501', '38113', NULL),
  ('Presidente Dutra', 'presidente-dutra', 'municipio'::"public"."enum_municipality_kind", 'Presidente Dutra', 'Irecê', '2925600', '38130', NULL),
  ('Presidente Jânio Quadros', 'presidente-janio-quadros', 'municipio'::"public"."enum_municipality_kind", 'Presidente Jânio Quadros', 'Sudoeste Baiano', '2925709', '38156', NULL),
  ('Presidente Tancredo Neves', 'presidente-tancredo-neves', 'municipio'::"public"."enum_municipality_kind", 'Presidente Tancredo Neves', 'Baixo Sul', '2925758', '38164', NULL),
  ('Queimadas', 'queimadas', 'municipio'::"public"."enum_municipality_kind", 'Queimadas', 'Sisal', '2925808', '38172', NULL),
  ('Quijingue', 'quijingue', 'municipio'::"public"."enum_municipality_kind", 'Quijingue', 'Sisal', '2925907', '38199', NULL),
  ('Quixabeira', 'quixabeira', 'municipio'::"public"."enum_municipality_kind", 'Quixabeira', 'Bacia do Jacuípe', '2925931', '39845', NULL),
  ('Rafael Jambeiro', 'rafael-jambeiro', 'municipio'::"public"."enum_municipality_kind", 'Rafael Jambeiro', 'Piemonte do Paraguaçu', '2925956', '39853', NULL),
  ('Remanso', 'remanso', 'municipio'::"public"."enum_municipality_kind", 'Remanso', 'Sertão do São Francisco', '2926004', '38210', NULL),
  ('Retirolândia', 'retirolandia', 'municipio'::"public"."enum_municipality_kind", 'Retirolândia', 'Sisal', '2926103', '38237', NULL),
  ('Riachão das Neves', 'riachao-das-neves', 'municipio'::"public"."enum_municipality_kind", 'Riachão das Neves', 'Bacia do Rio Grande', '2926202', '38253', NULL),
  ('Riachão do Jacuípe', 'riachao-do-jacuipe', 'municipio'::"public"."enum_municipality_kind", 'Riachão do Jacuípe', 'Bacia do Jacuípe', '2926301', '38270', NULL),
  ('Riacho de Santana', 'riacho-de-santana', 'municipio'::"public"."enum_municipality_kind", 'Riacho de Santana', 'Velho Chico', '2926400', '38296', NULL),
  ('Ribeira do Amparo', 'ribeira-do-amparo', 'municipio'::"public"."enum_municipality_kind", 'Ribeira do Amparo', 'Semiárido Nordeste II', '2926509', '38318', NULL),
  ('Ribeira do Pombal', 'ribeira-do-pombal', 'municipio'::"public"."enum_municipality_kind", 'Ribeira do Pombal', 'Semiárido Nordeste II', '2926608', '38334', NULL),
  ('Ribeirão do Largo', 'ribeirao-do-largo', 'municipio'::"public"."enum_municipality_kind", 'Ribeirão do Largo', 'Sudoeste Baiano', '2926657', '38342', NULL),
  ('Rio de Contas', 'rio-de-contas', 'municipio'::"public"."enum_municipality_kind", 'Rio de Contas', 'Chapada Diamantina', '2926707', '38350', NULL),
  ('Rio do Antônio', 'rio-do-antonio', 'municipio'::"public"."enum_municipality_kind", 'Rio do Antônio', 'Sertão Produtivo', '2926806', '38377', NULL),
  ('Rio do Pires', 'rio-do-pires', 'municipio'::"public"."enum_municipality_kind", 'Rio do Pires', 'Bacia do Paramirim', '2926905', '38393', NULL),
  ('Rio Real', 'rio-real', 'municipio'::"public"."enum_municipality_kind", 'Rio Real', 'Litoral Norte e Agreste Baiano', '2927002', '38415', NULL),
  ('Rodelas', 'rodelas', 'municipio'::"public"."enum_municipality_kind", 'Rodelas', 'Itaparica', '2927101', '38431', NULL),
  ('Ruy Barbosa', 'ruy-barbosa', 'municipio'::"public"."enum_municipality_kind", 'Ruy Barbosa', 'Piemonte do Paraguaçu', '2927200', '38458', NULL),
  ('Salinas da Margarida', 'salinas-da-margarida', 'municipio'::"public"."enum_municipality_kind", 'Salinas da Margarida', 'Recôncavo', '2927309', '38474', NULL),
  ('Salvador — ZE 1', 'salvador-ze-1', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 1),
  ('Salvador — ZE 2', 'salvador-ze-2', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 2),
  ('Salvador — ZE 3', 'salvador-ze-3', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 3),
  ('Salvador — ZE 4', 'salvador-ze-4', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 4),
  ('Salvador — ZE 5', 'salvador-ze-5', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 5),
  ('Salvador — ZE 6', 'salvador-ze-6', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 6),
  ('Salvador — ZE 7', 'salvador-ze-7', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 7),
  ('Salvador — ZE 8', 'salvador-ze-8', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 8),
  ('Salvador — ZE 9', 'salvador-ze-9', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 9),
  ('Salvador — ZE 10', 'salvador-ze-10', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 10),
  ('Salvador — ZE 11', 'salvador-ze-11', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 11),
  ('Salvador — ZE 12', 'salvador-ze-12', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 12),
  ('Salvador — ZE 13', 'salvador-ze-13', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 13),
  ('Salvador — ZE 14', 'salvador-ze-14', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 14),
  ('Salvador — ZE 15', 'salvador-ze-15', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 15),
  ('Salvador — ZE 16', 'salvador-ze-16', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 16),
  ('Salvador — ZE 17', 'salvador-ze-17', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 17),
  ('Salvador — ZE 18', 'salvador-ze-18', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 18),
  ('Salvador — ZE 19', 'salvador-ze-19', 'zona'::"public"."enum_municipality_kind", 'Salvador', 'Metropolitano de Salvador', '2927408', '38490', 19),
  ('Santa Bárbara', 'santa-barbara', 'municipio'::"public"."enum_municipality_kind", 'Santa Bárbara', 'Portal do Sertão', '2927507', '38512', NULL),
  ('Santa Brígida', 'santa-brigida', 'municipio'::"public"."enum_municipality_kind", 'Santa Brígida', 'Semiárido Nordeste II', '2927606', '38539', NULL),
  ('Santa Cruz Cabrália', 'santa-cruz-cabralia', 'municipio'::"public"."enum_municipality_kind", 'Santa Cruz Cabrália', 'Costa do Descobrimento', '2927705', '38555', NULL),
  ('Santa Cruz da Vitória', 'santa-cruz-da-vitoria', 'municipio'::"public"."enum_municipality_kind", 'Santa Cruz da Vitória', 'Médio Sudoeste da Bahia', '2927804', '38571', NULL),
  ('Santa Inês', 'santa-ines', 'municipio'::"public"."enum_municipality_kind", 'Santa Inês', 'Vale do Jiquiriçá', '2927903', '38598', NULL),
  ('Santa Luzia', 'santa-luzia', 'municipio'::"public"."enum_municipality_kind", 'Santa Luzia', 'Litoral Sul', '2928059', '39870', NULL),
  ('Santa Maria da Vitória', 'santa-maria-da-vitoria', 'municipio'::"public"."enum_municipality_kind", 'Santa Maria da Vitória', 'Bacia do Rio Corrente', '2928109', '38636', NULL),
  ('Santa Rita de Cássia', 'santa-rita-de-cassia', 'municipio'::"public"."enum_municipality_kind", 'Santa Rita de Cássia', 'Bacia do Rio Grande', '2928406', '35491', NULL),
  ('Santa Teresinha', 'santa-teresinha', 'municipio'::"public"."enum_municipality_kind", 'Santa Teresinha', 'Piemonte do Paraguaçu', '2928505', '38695', NULL),
  ('Santaluz', 'santaluz', 'municipio'::"public"."enum_municipality_kind", 'Santaluz', 'Sisal', '2928000', '38610', NULL),
  ('Santana', 'santana', 'municipio'::"public"."enum_municipality_kind", 'Santana', 'Bacia do Rio Corrente', '2928208', '38652', NULL),
  ('Santanópolis', 'santanopolis', 'municipio'::"public"."enum_municipality_kind", 'Santanópolis', 'Portal do Sertão', '2928307', '38679', NULL),
  ('Santo Amaro', 'santo-amaro', 'municipio'::"public"."enum_municipality_kind", 'Santo Amaro', 'Recôncavo', '2928604', '38717', NULL),
  ('Santo Antônio de Jesus', 'santo-antonio-de-jesus', 'municipio'::"public"."enum_municipality_kind", 'Santo Antônio de Jesus', 'Recôncavo', '2928703', '38733', NULL),
  ('Santo Estêvão', 'santo-estevao', 'municipio'::"public"."enum_municipality_kind", 'Santo Estêvão', 'Portal do Sertão', '2928802', '38750', NULL),
  ('São Desidério', 'sao-desiderio', 'municipio'::"public"."enum_municipality_kind", 'São Desidério', 'Bacia do Rio Grande', '2928901', '38776', NULL),
  ('São Domingos', 'sao-domingos', 'municipio'::"public"."enum_municipality_kind", 'São Domingos', 'Sisal', '2928950', '38806', NULL),
  ('São Felipe', 'sao-felipe', 'municipio'::"public"."enum_municipality_kind", 'São Felipe', 'Recôncavo', '2929107', '38814', NULL),
  ('São Félix', 'sao-felix', 'municipio'::"public"."enum_municipality_kind", 'São Félix', 'Recôncavo', '2929008', '38792', NULL),
  ('São Félix do Coribe', 'sao-felix-do-coribe', 'municipio'::"public"."enum_municipality_kind", 'São Félix do Coribe', 'Bacia do Rio Corrente', '2929057', '38822', NULL),
  ('São Francisco do Conde', 'sao-francisco-do-conde', 'municipio'::"public"."enum_municipality_kind", 'São Francisco do Conde', 'Metropolitano de Salvador', '2929206', '38830', NULL),
  ('São Gabriel', 'sao-gabriel', 'municipio'::"public"."enum_municipality_kind", 'São Gabriel', 'Irecê', '2929255', '39896', NULL),
  ('São Gonçalo dos Campos', 'sao-goncalo-dos-campos', 'municipio'::"public"."enum_municipality_kind", 'São Gonçalo dos Campos', 'Portal do Sertão', '2929305', '38857', NULL),
  ('São José da Vitória', 'sao-jose-da-vitoria', 'municipio'::"public"."enum_municipality_kind", 'São José da Vitória', 'Litoral Sul', '2929354', '39926', NULL),
  ('São José do Jacuípe', 'sao-jose-do-jacuipe', 'municipio'::"public"."enum_municipality_kind", 'São José do Jacuípe', 'Bacia do Jacuípe', '2929370', '38865', NULL),
  ('São Miguel das Matas', 'sao-miguel-das-matas', 'municipio'::"public"."enum_municipality_kind", 'São Miguel das Matas', 'Vale do Jiquiriçá', '2929404', '38873', NULL),
  ('São Sebastião do Passé', 'sao-sebastiao-do-passe', 'municipio'::"public"."enum_municipality_kind", 'São Sebastião do Passé', 'Metropolitano de Salvador', '2929503', '38890', NULL),
  ('Sapeaçu', 'sapeacu', 'municipio'::"public"."enum_municipality_kind", 'Sapeaçu', 'Recôncavo', '2929602', '38911', NULL),
  ('Sátiro Dias', 'satiro-dias', 'municipio'::"public"."enum_municipality_kind", 'Sátiro Dias', 'Litoral Norte e Agreste Baiano', '2929701', '38938', NULL),
  ('Saubara', 'saubara', 'municipio'::"public"."enum_municipality_kind", 'Saubara', 'Recôncavo', '2929750', '38946', NULL),
  ('Saúde', 'saude', 'municipio'::"public"."enum_municipality_kind", 'Saúde', 'Piemonte da Diamantina', '2929800', '38954', NULL),
  ('Seabra', 'seabra', 'municipio'::"public"."enum_municipality_kind", 'Seabra', 'Chapada Diamantina', '2929909', '38970', NULL),
  ('Sebastião Laranjeiras', 'sebastiao-laranjeiras', 'municipio'::"public"."enum_municipality_kind", 'Sebastião Laranjeiras', 'Sertão Produtivo', '2930006', '38997', NULL),
  ('Senhor do Bonfim', 'senhor-do-bonfim', 'municipio'::"public"."enum_municipality_kind", 'Senhor do Bonfim', 'Piemonte Norte do Itapicuru', '2930105', '39012', NULL),
  ('Sento Sé', 'sento-se', 'municipio'::"public"."enum_municipality_kind", 'Sento Sé', 'Sertão do São Francisco', '2930204', '39039', NULL),
  ('Serra do Ramalho', 'serra-do-ramalho', 'municipio'::"public"."enum_municipality_kind", 'Serra do Ramalho', 'Velho Chico', '2930154', '39047', NULL),
  ('Serra Dourada', 'serra-dourada', 'municipio'::"public"."enum_municipality_kind", 'Serra Dourada', 'Bacia do Rio Corrente', '2930303', '39055', NULL),
  ('Serra Preta', 'serra-preta', 'municipio'::"public"."enum_municipality_kind", 'Serra Preta', 'Bacia do Jacuípe', '2930402', '39071', NULL),
  ('Serrinha', 'serrinha', 'municipio'::"public"."enum_municipality_kind", 'Serrinha', 'Sisal', '2930501', '39098', NULL),
  ('Serrolândia', 'serrolandia', 'municipio'::"public"."enum_municipality_kind", 'Serrolândia', 'Piemonte da Diamantina', '2930600', '39110', NULL),
  ('Simões Filho', 'simoes-filho', 'municipio'::"public"."enum_municipality_kind", 'Simões Filho', 'Metropolitano de Salvador', '2930709', '39136', NULL),
  ('Sítio do Mato', 'sitio-do-mato', 'municipio'::"public"."enum_municipality_kind", 'Sítio do Mato', 'Velho Chico', '2930758', '39144', NULL),
  ('Sítio do Quinto', 'sitio-do-quinto', 'municipio'::"public"."enum_municipality_kind", 'Sítio do Quinto', 'Semiárido Nordeste II', '2930766', '39900', NULL),
  ('Sobradinho', 'sobradinho', 'municipio'::"public"."enum_municipality_kind", 'Sobradinho', 'Sertão do São Francisco', '2930774', '39985', NULL),
  ('Souto Soares', 'souto-soares', 'municipio'::"public"."enum_municipality_kind", 'Souto Soares', 'Chapada Diamantina', '2930808', '39152', NULL),
  ('Tabocas do Brejo Velho', 'tabocas-do-brejo-velho', 'municipio'::"public"."enum_municipality_kind", 'Tabocas do Brejo Velho', 'Bacia do Rio Corrente', '2930907', '39179', NULL),
  ('Tanhaçu', 'tanhacu', 'municipio'::"public"."enum_municipality_kind", 'Tanhaçu', 'Sertão Produtivo', '2931004', '39195', NULL),
  ('Tanque Novo', 'tanque-novo', 'municipio'::"public"."enum_municipality_kind", 'Tanque Novo', 'Sertão Produtivo', '2931053', '39918', NULL),
  ('Tanquinho', 'tanquinho', 'municipio'::"public"."enum_municipality_kind", 'Tanquinho', 'Portal do Sertão', '2931103', '39217', NULL),
  ('Taperoá', 'taperoa', 'municipio'::"public"."enum_municipality_kind", 'Taperoá', 'Baixo Sul', '2931202', '39233', NULL),
  ('Tapiramutá', 'tapiramuta', 'municipio'::"public"."enum_municipality_kind", 'Tapiramutá', 'Piemonte do Paraguaçu', '2931301', '39250', NULL),
  ('Teixeira de Freitas', 'teixeira-de-freitas', 'municipio'::"public"."enum_municipality_kind", 'Teixeira de Freitas', 'Extremo Sul', '2931350', '39934', NULL),
  ('Teodoro Sampaio', 'teodoro-sampaio', 'municipio'::"public"."enum_municipality_kind", 'Teodoro Sampaio', 'Portal do Sertão', '2931400', '39276', NULL),
  ('Teofilândia', 'teofilandia', 'municipio'::"public"."enum_municipality_kind", 'Teofilândia', 'Sisal', '2931509', '39292', NULL),
  ('Teolândia', 'teolandia', 'municipio'::"public"."enum_municipality_kind", 'Teolândia', 'Baixo Sul', '2931608', '39314', NULL),
  ('Terra Nova', 'terra-nova', 'municipio'::"public"."enum_municipality_kind", 'Terra Nova', 'Portal do Sertão', '2931707', '39330', NULL),
  ('Tremedal', 'tremedal', 'municipio'::"public"."enum_municipality_kind", 'Tremedal', 'Sudoeste Baiano', '2931806', '39357', NULL),
  ('Tucano', 'tucano', 'municipio'::"public"."enum_municipality_kind", 'Tucano', 'Sisal', '2931905', '39373', NULL),
  ('Uauá', 'uaua', 'municipio'::"public"."enum_municipality_kind", 'Uauá', 'Sertão do São Francisco', '2932002', '39390', NULL),
  ('Ubaíra', 'ubaira', 'municipio'::"public"."enum_municipality_kind", 'Ubaíra', 'Vale do Jiquiriçá', '2932101', '39411', NULL),
  ('Ubaitaba', 'ubaitaba', 'municipio'::"public"."enum_municipality_kind", 'Ubaitaba', 'Litoral Sul', '2932200', '39438', NULL),
  ('Ubatã', 'ubata', 'municipio'::"public"."enum_municipality_kind", 'Ubatã', 'Médio Rio de Contas', '2932309', '39454', NULL),
  ('Uibaí', 'uibai', 'municipio'::"public"."enum_municipality_kind", 'Uibaí', 'Irecê', '2932408', '39470', NULL),
  ('Umburanas', 'umburanas', 'municipio'::"public"."enum_municipality_kind", 'Umburanas', 'Piemonte da Diamantina', '2932457', '39489', NULL),
  ('Una', 'una', 'municipio'::"public"."enum_municipality_kind", 'Una', 'Litoral Sul', '2932507', '39497', NULL),
  ('Urandi', 'urandi', 'municipio'::"public"."enum_municipality_kind", 'Urandi', 'Sertão Produtivo', '2932606', '39519', NULL),
  ('Uruçuca', 'urucuca', 'municipio'::"public"."enum_municipality_kind", 'Uruçuca', 'Litoral Sul', '2932705', '39535', NULL),
  ('Utinga', 'utinga', 'municipio'::"public"."enum_municipality_kind", 'Utinga', 'Chapada Diamantina', '2932804', '39551', NULL),
  ('Valença', 'valenca', 'municipio'::"public"."enum_municipality_kind", 'Valença', 'Baixo Sul', '2932903', '39578', NULL),
  ('Valente', 'valente', 'municipio'::"public"."enum_municipality_kind", 'Valente', 'Sisal', '2933000', '39594', NULL),
  ('Várzea da Roça', 'varzea-da-roca', 'municipio'::"public"."enum_municipality_kind", 'Várzea da Roça', 'Bacia do Jacuípe', '2933059', '39977', NULL),
  ('Várzea do Poço', 'varzea-do-poco', 'municipio'::"public"."enum_municipality_kind", 'Várzea do Poço', 'Bacia do Jacuípe', '2933109', '39616', NULL),
  ('Várzea Nova', 'varzea-nova', 'municipio'::"public"."enum_municipality_kind", 'Várzea Nova', 'Piemonte da Diamantina', '2933158', '39950', NULL),
  ('Varzedo', 'varzedo', 'municipio'::"public"."enum_municipality_kind", 'Varzedo', 'Recôncavo', '2933174', '39624', NULL),
  ('Vera Cruz', 'vera-cruz', 'municipio'::"public"."enum_municipality_kind", 'Vera Cruz', 'Metropolitano de Salvador', '2933208', '39632', NULL),
  ('Vereda', 'vereda', 'municipio'::"public"."enum_municipality_kind", 'Vereda', 'Extremo Sul', '2933257', '39640', NULL),
  ('Vitória da Conquista', 'vitoria-da-conquista', 'municipio'::"public"."enum_municipality_kind", 'Vitória da Conquista', 'Sudoeste Baiano', '2933307', '39659', NULL),
  ('Wagner', 'wagner', 'municipio'::"public"."enum_municipality_kind", 'Wagner', 'Chapada Diamantina', '2933406', '39675', NULL),
  ('Wanderley', 'wanderley', 'municipio'::"public"."enum_municipality_kind", 'Wanderley', 'Bacia do Rio Grande', '2933455', '39993', NULL),
  ('Wenceslau Guimarães', 'wenceslau-guimaraes', 'municipio'::"public"."enum_municipality_kind", 'Wenceslau Guimarães', 'Baixo Sul', '2933505', '39691', NULL),
  ('Xique-Xique', 'xique-xique', 'municipio'::"public"."enum_municipality_kind", 'Xique-Xique', 'Irecê', '2933604', '39713', NULL)
    ON CONFLICT DO NOTHING;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  throw new Error('remodel_municipalities is irreversible')
}
